import type { Metadata } from "next";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Marquee from "./components/Marquee";

const notoSerifBenglai = Noto_Serif_Bengali({

  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBenglai.className} h-full antialiased`}
    >
<body className="flex min-h-screen flex-col">
  <Header />

  <Marquee />

  <main className="mx-auto mt-5 w-full max-w-7xl flex-1 px-4 sm:px-6 lg:px-8">
    {children}
  </main>

  <Footer />
</body>
    </html>
  );
}
